// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package com_ta04_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// User is a message for user
type User struct {
	Id                     int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName              string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName               string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username               string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password               string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	EmailAddress           string   `protobuf:"bytes,6,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	PhoneNumber            string   `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	DateOfBirth            string   `protobuf:"bytes,8,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Address                string   `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Role                   string   `protobuf:"bytes,10,opt,name=role,proto3" json:"role,omitempty"`
	CreditCardNumber       string   `protobuf:"bytes,11,opt,name=credit_card_number,json=creditCardNumber,proto3" json:"credit_card_number,omitempty"`
	CreditCardType         string   `protobuf:"bytes,12,opt,name=credit_card_type,json=creditCardType,proto3" json:"credit_card_type,omitempty"`
	CreditCardExpiredMonth string   `protobuf:"bytes,13,opt,name=credit_card_expired_month,json=creditCardExpiredMonth,proto3" json:"credit_card_expired_month,omitempty"`
	CreditCardExpiredYear  string   `protobuf:"bytes,14,opt,name=credit_card_expired_year,json=creditCardExpiredYear,proto3" json:"credit_card_expired_year,omitempty"`
	CreditCardCvv          string   `protobuf:"bytes,15,opt,name=credit_card_cvv,json=creditCardCvv,proto3" json:"credit_card_cvv,omitempty"`
	Status                 string   `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	N                      string   `protobuf:"bytes,17,opt,name=n,proto3" json:"n,omitempty"`
	G                      string   `protobuf:"bytes,18,opt,name=g,proto3" json:"g,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetDateOfBirth() string {
	if m != nil {
		return m.DateOfBirth
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetCreditCardNumber() string {
	if m != nil {
		return m.CreditCardNumber
	}
	return ""
}

func (m *User) GetCreditCardType() string {
	if m != nil {
		return m.CreditCardType
	}
	return ""
}

func (m *User) GetCreditCardExpiredMonth() string {
	if m != nil {
		return m.CreditCardExpiredMonth
	}
	return ""
}

func (m *User) GetCreditCardExpiredYear() string {
	if m != nil {
		return m.CreditCardExpiredYear
	}
	return ""
}

func (m *User) GetCreditCardCvv() string {
	if m != nil {
		return m.CreditCardCvv
	}
	return ""
}

func (m *User) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *User) GetN() string {
	if m != nil {
		return m.N
	}
	return ""
}

func (m *User) GetG() string {
	if m != nil {
		return m.G
	}
	return ""
}

// IndexUsersRequest is a message for IndexUsers
type IndexUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexUsersRequest) Reset()         { *m = IndexUsersRequest{} }
func (m *IndexUsersRequest) String() string { return proto.CompactTextString(m) }
func (*IndexUsersRequest) ProtoMessage()    {}
func (*IndexUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *IndexUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexUsersRequest.Unmarshal(m, b)
}
func (m *IndexUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexUsersRequest.Marshal(b, m, deterministic)
}
func (m *IndexUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexUsersRequest.Merge(m, src)
}
func (m *IndexUsersRequest) XXX_Size() int {
	return xxx_messageInfo_IndexUsersRequest.Size(m)
}
func (m *IndexUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexUsersRequest proto.InternalMessageInfo

// Response is a response message
type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Users                []*User  `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

// Error is an error message
type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "com.ta04.srv.user.User")
	proto.RegisterType((*IndexUsersRequest)(nil), "com.ta04.srv.user.IndexUsersRequest")
	proto.RegisterType((*Response)(nil), "com.ta04.srv.user.Response")
	proto.RegisterType((*Error)(nil), "com.ta04.srv.user.Error")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0x66, 0xbb, 0xbb, 0xed, 0x66, 0xb2, 0xdb, 0x9f, 0x41, 0x14, 0xd3, 0x0a, 0xa9, 0x04, 0x84,
	0x2a, 0x01, 0x11, 0x2a, 0x20, 0xc4, 0x91, 0xfe, 0x1c, 0x90, 0xa0, 0x88, 0x94, 0x1e, 0x38, 0x45,
	0x6e, 0x3c, 0xed, 0x46, 0x6a, 0xe2, 0x60, 0x7b, 0xd3, 0xee, 0x8b, 0xf0, 0x44, 0x1c, 0x79, 0x28,
	0xe4, 0x49, 0xa3, 0xad, 0xd4, 0x05, 0x24, 0x7a, 0xf3, 0x7c, 0x7f, 0x63, 0x3b, 0xe3, 0x00, 0x4c,
	0x2c, 0x99, 0xb8, 0x32, 0xda, 0x69, 0x5c, 0xcb, 0x74, 0x11, 0x3b, 0xf9, 0xf2, 0x75, 0x6c, 0x4d,
	0x1d, 0x7b, 0x22, 0xfa, 0xd5, 0x83, 0xde, 0xb1, 0x25, 0x83, 0xcb, 0xb0, 0x90, 0x2b, 0xd1, 0xd9,
	0xea, 0x6c, 0xf7, 0x93, 0x85, 0x5c, 0xe1, 0x43, 0x80, 0xd3, 0xdc, 0x58, 0x97, 0x96, 0xb2, 0x20,
	0xb1, 0xb0, 0xd5, 0xd9, 0x0e, 0x92, 0x80, 0x91, 0x43, 0x59, 0x10, 0x6e, 0x42, 0x70, 0x2e, 0x5b,
	0xb6, 0xcb, 0xec, 0xc0, 0x03, 0x4c, 0x6e, 0xc0, 0xc0, 0x87, 0x33, 0xd7, 0x6b, 0xb8, 0xb6, 0xf6,
	0x5c, 0x25, 0xad, 0xbd, 0xd0, 0x46, 0x89, 0x7e, 0xc3, 0xb5, 0x35, 0x3e, 0x86, 0x11, 0x15, 0x32,
	0x3f, 0x4f, 0xa5, 0x52, 0x86, 0xac, 0x15, 0x8b, 0x2c, 0x18, 0x32, 0xf8, 0xbe, 0xc1, 0xf0, 0x11,
	0x0c, 0xab, 0xb1, 0x2e, 0x29, 0x2d, 0x27, 0xc5, 0x09, 0x19, 0xb1, 0xc4, 0x9a, 0x90, 0xb1, 0x43,
	0x86, 0x30, 0x82, 0x91, 0x92, 0x8e, 0x52, 0x7d, 0x9a, 0x9e, 0xe4, 0xc6, 0x8d, 0xc5, 0xa0, 0xd1,
	0x78, 0xf0, 0xf3, 0xe9, 0xae, 0x87, 0x50, 0xc0, 0x52, 0xdb, 0x25, 0x60, 0xb6, 0x2d, 0x11, 0xa1,
	0x67, 0xf4, 0x39, 0x09, 0x60, 0x98, 0xd7, 0xf8, 0x1c, 0x30, 0x33, 0xa4, 0x72, 0x97, 0x66, 0xd2,
	0xa8, 0xb6, 0x75, 0xc8, 0x8a, 0xd5, 0x86, 0xd9, 0x93, 0x46, 0x5d, 0xf5, 0xdf, 0x86, 0xd5, 0xeb,
	0x6a, 0x37, 0xad, 0x48, 0x0c, 0x59, 0xbb, 0x3c, 0xd3, 0x7e, 0x9d, 0x56, 0x84, 0xef, 0xe0, 0xc1,
	0x75, 0x25, 0x5d, 0x56, 0xb9, 0x21, 0x95, 0x16, 0xba, 0x74, 0x63, 0x31, 0x62, 0xcb, 0xfa, 0xcc,
	0x72, 0xd0, 0xd0, 0x9f, 0x3c, 0x8b, 0x6f, 0x41, 0xcc, 0xb3, 0x4e, 0x49, 0x1a, 0xb1, 0xcc, 0xce,
	0x7b, 0x37, 0x9c, 0xdf, 0x48, 0x1a, 0x7c, 0x0a, 0x2b, 0xd7, 0x8d, 0x59, 0x5d, 0x8b, 0x15, 0xd6,
	0x8f, 0x66, 0xfa, 0xbd, 0xba, 0xc6, 0x75, 0x58, 0xb4, 0x4e, 0xba, 0x89, 0x15, 0xab, 0x4c, 0x5f,
	0x55, 0x38, 0x84, 0x4e, 0x29, 0xd6, 0x18, 0xea, 0x94, 0xbe, 0x3a, 0x13, 0xd8, 0x54, 0x67, 0xd1,
	0x5d, 0x58, 0xfb, 0x50, 0x2a, 0xba, 0xf4, 0x23, 0x65, 0x13, 0xfa, 0x3e, 0x21, 0xeb, 0xa2, 0x1f,
	0x1d, 0x18, 0x24, 0x64, 0x2b, 0x5d, 0x5a, 0xc2, 0x67, 0xd0, 0xf3, 0xb3, 0xc0, 0x93, 0x16, 0xee,
	0xdc, 0x8f, 0x6f, 0x8c, 0x64, 0xec, 0xbd, 0x09, 0x8b, 0x30, 0x86, 0x3e, 0x19, 0xa3, 0x0d, 0xcf,
	0x5f, 0xb8, 0x23, 0xe6, 0xa8, 0x0f, 0x3c, 0x9f, 0x34, 0x32, 0x7c, 0x01, 0x7d, 0x0f, 0x5a, 0xd1,
	0xdd, 0xea, 0xfe, 0x2d, 0xbd, 0x51, 0x45, 0x6f, 0xa0, 0xcf, 0x76, 0xff, 0xc9, 0x33, 0xad, 0x88,
	0x37, 0x15, 0x24, 0xbc, 0xf6, 0x03, 0x52, 0x90, 0xb5, 0xf2, 0xac, 0x9d, 0xfe, 0xb6, 0xdc, 0xf9,
	0xd9, 0x85, 0xd0, 0xc7, 0x1c, 0x91, 0xa9, 0xf3, 0x8c, 0xf0, 0x0b, 0xc0, 0xec, 0xd0, 0xf8, 0x64,
	0x4e, 0xd3, 0x1b, 0x77, 0xb2, 0xb1, 0x39, 0x47, 0xd5, 0xde, 0x51, 0x74, 0x07, 0x77, 0x61, 0x70,
	0x34, 0xd6, 0x17, 0xfc, 0x32, 0xff, 0x74, 0x8a, 0x7f, 0x65, 0x7c, 0x04, 0x6c, 0x33, 0x76, 0xa7,
	0xc7, 0xed, 0xfb, 0xfb, 0xdf, 0xb4, 0x3d, 0x08, 0x8e, 0x9c, 0x36, 0x74, 0xab, 0x2d, 0xed, 0x03,
	0x1c, 0x57, 0xfe, 0x15, 0xde, 0x2a, 0xe5, 0x00, 0xc2, 0x7d, 0xb2, 0xce, 0xe8, 0xe9, 0x6d, 0x62,
	0x4e, 0x16, 0xf9, 0xa7, 0xf8, 0xea, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x56, 0x55, 0x6d,
	0x22, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserServiceClient interface {
	// IndexUsers is a method to index all users
	IndexUsers(ctx context.Context, in *IndexUsersRequest, opts ...client.CallOption) (*Response, error)
	// ShowUser is a method to show a user
	ShowUser(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	// ShowUser is a method to show a user by the user's username
	ShowUserByUsername(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	// StoreUser is a method to store a new user
	StoreUser(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	// UpdateUser is a method to update a user
	UpdateUser(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	// DestroyUser is a method to delete a user
	DestroyUser(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
}

type userServiceClient struct {
	c           client.Client
	serviceName string
}

func NewUserServiceClient(serviceName string, c client.Client) UserServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "com.ta04.srv.user"
	}
	return &userServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceClient) IndexUsers(ctx context.Context, in *IndexUsersRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.IndexUsers", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ShowUser(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.ShowUser", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ShowUserByUsername(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.ShowUserByUsername", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) StoreUser(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.StoreUser", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.UpdateUser", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DestroyUser(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.DestroyUser", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	// IndexUsers is a method to index all users
	IndexUsers(context.Context, *IndexUsersRequest, *Response) error
	// ShowUser is a method to show a user
	ShowUser(context.Context, *User, *Response) error
	// ShowUser is a method to show a user by the user's username
	ShowUserByUsername(context.Context, *User, *Response) error
	// StoreUser is a method to store a new user
	StoreUser(context.Context, *User, *Response) error
	// UpdateUser is a method to update a user
	UpdateUser(context.Context, *User, *Response) error
	// DestroyUser is a method to delete a user
	DestroyUser(context.Context, *User, *Response) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserService{hdlr}, opts...))
}

type UserService struct {
	UserServiceHandler
}

func (h *UserService) IndexUsers(ctx context.Context, in *IndexUsersRequest, out *Response) error {
	return h.UserServiceHandler.IndexUsers(ctx, in, out)
}

func (h *UserService) ShowUser(ctx context.Context, in *User, out *Response) error {
	return h.UserServiceHandler.ShowUser(ctx, in, out)
}

func (h *UserService) ShowUserByUsername(ctx context.Context, in *User, out *Response) error {
	return h.UserServiceHandler.ShowUserByUsername(ctx, in, out)
}

func (h *UserService) StoreUser(ctx context.Context, in *User, out *Response) error {
	return h.UserServiceHandler.StoreUser(ctx, in, out)
}

func (h *UserService) UpdateUser(ctx context.Context, in *User, out *Response) error {
	return h.UserServiceHandler.UpdateUser(ctx, in, out)
}

func (h *UserService) DestroyUser(ctx context.Context, in *User, out *Response) error {
	return h.UserServiceHandler.DestroyUser(ctx, in, out)
}
